os: linux
language: rust
rust:
  - stable
cache: cargo
git:
    lfs_skip_smudge: true
before_script:
  - echo -e "machine github.com\n  login $GITHUB_TOKEN" > ~/.netrc
  - git lfs pull
script:
  - cargo test
  - cargo build --release
before_deploy:
  - curl -sSL https://deb.nodesource.com/gpgkey/nodesource.gpg.key | sudo apt-key add -
  - sudo add-apt-repository "deb https://deb.nodesource.com/node_8.x $(lsb_release -s -c) main" -y
  - sudo apt-get update -q
  - sudo apt-get install nodejs -y
  - sudo npm i -g npm
  - sudo npm i -g --unsafe-perm now
deploy:
  - provider: script
    script: now --public --target staging --token $NOW_TOKEN
    skip_cleanup: true
    on:
      all_branches: true
      tags: false
      condition: $TRAVIS_RUST_VERSION = "stable"
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: "LpevEM9mbUDnMbhoRdkT7mE+LfcJXybXCqt8dDZezHahHElMNqBw6dgJe0dkEMM3Tuc8U+Eu8wv16LHw8syJVkAtOWNGKpi80eEVLYNLUY5aSy3GfEScSRETVgOjoNaect5xXFYuAsaTCxDtEEHL7i/bVzb78qgABpihY8vOUP0hrOiIQ8Rpk6nMnBc6cLHzbJOMD0DmrZl86HHRXSmK847m6WK5qeFPecMl/JiusXzvG7qKVaaQmL7FRuELZJHosWVO8dGVSGOSfiGx+Rp+PP0+Pa2Y8YQW/mjbS9O4o7HrQhsRhX/rBumXyLxSTXCcNV3X9qjtDDVPVtqq2XsLK+cnFp4UHGQU95U3ntd7kl81TYinUjYUSpgPBiVNPKJIFokMQT13c2mFa4e7YoOvrXyXJf2jKB4Sk34hcnwAvp3a+uB43mbVNlGzxyzab2irFBL/MHDCSb9aDVrW/+jvMMM12KcxlfaPxe80J8sTTD9kbeTz8kvcatcpwPUQJRL6qxcbeSkKo+uVomi2k0lLS4Ms/tSL2YKrHBCnC0MnWSfk7L+QXc7gSLL5Ykf7nv2+vmMcGjEL2bj7otnH8Bjphf0N4woCMec617d9KsqGSWxnCJRNMMbjR/QkNESjWf6agtapIYm3ABVzZoVKWqqvmcBlz6w9XpB6MNxzAcsb/kY="
    file: target/release/ipapi
    on:
      branch: master
      tags: true
      condition: $TRAVIS_RUST_VERSION = "stable"
  - provider: script
    script: now  --target production --token $NOW_TOKEN && now rm ipapi --safe --yes --token $NOW_TOKEN
    skip_cleanup: true
    on:
      branch: master
      tags: true
      condition: $TRAVIS_RUST_VERSION = "stable"
